import "./globals.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
  <div className="relative min-h-screen bg-orange-600 text-slate-900">
    {/* Fixed background logo */}
    <div className="pointer-events-none fixed inset-0 z-0 flex items-center justify-center">
      <img
        src="/logo.png"
        alt=""
        className="opacity-100 w-[600px] max-w-[90vw]"
      />
    </div>

    {/* App content */}
    <div className="relative z-10">
      {children}
    </div>
  </div>
</body>
    </html>
  )
}
